[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Futureproof Local"
authors = [{name = "Joe McAlister", email = "joe@joe.ac"}]
dynamic = ["version", "description"]
